<?php

namespace Database\Seeders;

use App\Models\DeliveryCategory;
use App\Models\Service;
use App\Support\ServiceContentNormalizer;
use Illuminate\Database\Seeder;

/**
 * Seeds every service in every delivery category with SEO-rich content
 * (meta_title 40-60 chars, meta_description 120-160 chars, og_*, schema_type, image_alt, etc.).
 *
 * Run with: php artisan db:seed --class=AllServicesSeeder
 *
 * Idempotent: uses updateOrCreate keyed on slug, so it is safe to re-run.
 * Image paths are wired to storage/app/public/services/{slug}/hero.png. Drop a real
 * photo there (or upload via the admin UI) and the public page will pick it up.
 */
class AllServicesSeeder extends Seeder
{
    public function run(): void
    {
        $catBySlug = DeliveryCategory::query()
            ->whereIn('slug', ['web-development', 'mobile-development', 'ai-solutions', 'digital-marketing'])
            ->pluck('id', 'slug');

        foreach ($this->services() as $position => $svc) {
            $catSlug = $svc['category'];
            $slug = $svc['slug'];

            $hero = $svc['hero'];
            $tech = $svc['tech'];
            $outcomes = $svc['outcomes'];
            $snapshot = $svc['snapshot'] ?? [];

            $defaults = ServiceContentNormalizer::defaultStructure();
            $content = [
                'hero' => array_replace($defaults['hero'], $hero),
                'tech' => array_replace($defaults['tech'], $tech),
                'outcomes' => array_replace($defaults['outcomes'], $outcomes),
                'snapshot' => array_replace($defaults['snapshot'], $snapshot),
            ];

            Service::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'delivery_category_id' => $catBySlug->get($catSlug),
                    'title' => $svc['title'],
                    'description' => $svc['summary'],
                    'icon' => $svc['icon'],
                    'sort_order' => $position,
                    'is_active' => true,

                    'meta_title' => $svc['meta_title'],
                    'meta_description' => $svc['meta_description'],
                    'meta_keywords' => $svc['meta_keywords'],
                    'og_title' => $svc['og_title'],
                    'og_description' => $svc['og_description'],
                    'noindex' => false,
                    'canonical_url' => null,
                    'schema_type' => $svc['schema_type'] ?? 'Service',

                    'hero_image_path' => 'services/'.$slug.'/hero.jpg',
                    'tech_image_path' => null,
                    'outcomes_image_path' => null,
                    'snapshot_image_path' => null,
                    'og_image_path' => null,

                    'content' => $content,
                ]
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function services(): array
    {
        return [
            // ============================== WEB DEVELOPMENT ==============================
            [
                'category' => 'web-development',
                'slug' => 'website-ui-ux',
                'title' => 'Website UI/UX Design',
                'icon' => 'LayoutTemplate',
                'summary' => 'Research-backed UI, accessible components, and a handoff your engineers can ship with confidence.',
                'meta_title' => 'Website UI/UX Design Services | Conversion-Focused Interfaces',
                'meta_description' => 'Research-backed website UI/UX design with accessible components, design systems, and conversion-tuned flows ready for engineering hand-off.',
                'meta_keywords' => 'website ui ux design, web design services, design systems, accessible web design, conversion-focused ui',
                'og_title' => 'Website UI/UX Design that Converts',
                'og_description' => 'Modern, accessible, conversion-focused web interfaces backed by research and a documented design system.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Website UI / UX',
                    'heading_prefix' => 'We structure',
                    'heading_highlight' => 'ideas',
                    'subhead' => 'into clear, beautiful products',
                    'description' => 'Research, flows, design systems, and refined visual craft so the first interaction with your product feels intentional, accessible, and premium.',
                    'chips' => [
                        ['icon' => 'Layers', 'label' => 'Design systems'],
                        ['icon' => 'Palette', 'label' => 'Visual craft'],
                        ['icon' => 'Accessibility', 'label' => 'WCAG-aligned'],
                    ],
                    'primary_cta_label' => 'Start a project',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'Wireframes, components, and a polished marketing landing page composed in a modern design tool.',
                    'caption_eyebrow' => 'Interface layer',
                    'caption_text' => 'Production-ready UI — clarity, motion, and trust.',
                ],
                'tech' => [
                    'eyebrow' => 'UI stack',
                    'heading_prefix' => 'Design tools',
                    'heading_highlight' => '& delivery',
                    'description' => 'A pragmatic toolchain that produces real components, real tokens, and real handoff that engineers can build from on day one.',
                    'items' => [
                        ['name' => 'Figma', 'slug' => 'figma'],
                        ['name' => 'Tailwind CSS', 'slug' => 'tailwindcss'],
                        ['name' => 'Storybook', 'slug' => 'storybook'],
                        ['name' => 'React', 'slug' => 'react'],
                        ['name' => 'Vue.js', 'slug' => 'vuedotjs'],
                        ['name' => 'TypeScript', 'slug' => 'typescript'],
                    ],
                    'cta_label' => 'Discuss your UI/UX',
                    'cta_href' => '/contact',
                    'image_alt' => 'Logos for Figma, Tailwind CSS, Storybook, and a modern frontend stack.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'What we deliver',
                    'description' => 'Research-backed UI, accessible components, and a handoff your engineers can ship with confidence.',
                    'cards' => [
                        ['icon' => 'LayoutTemplate', 'title' => 'Product & marketing sites', 'description' => 'IA, key screens, and responsive layouts that match your brand and performance budget.'],
                        ['icon' => 'MousePointer2', 'title' => 'Design systems', 'description' => 'Tokens, components, and documentation so every new feature stays on-brand.'],
                        ['icon' => 'Palette', 'title' => 'UX refinement', 'description' => 'Flow fixes, usability passes, and measurable improvements to completion and retention.'],
                    ],
                    'cta_label' => 'Discuss your UI / UX',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'web-development',
                'slug' => 'cms-solutions',
                'title' => 'CMS Solutions',
                'icon' => 'FileStack',
                'summary' => 'Headless and traditional CMS builds with editor-friendly workflows and ship-ready performance.',
                'meta_title' => 'CMS Development Services | Headless & Traditional CMS Builds',
                'meta_description' => 'Custom CMS development for editorial teams. Headless CMS (Sanity, Strapi, Contentful) and Laravel/WordPress builds with fast publishing workflows.',
                'meta_keywords' => 'cms development, headless cms, sanity, strapi, contentful, wordpress, laravel cms',
                'og_title' => 'Custom CMS Development',
                'og_description' => 'Editor-friendly headless and traditional CMS solutions with fast publishing workflows.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'CMS solutions',
                    'heading_prefix' => 'Content systems',
                    'heading_highlight' => 'editors love',
                    'subhead' => 'and engineers can extend',
                    'description' => 'Headless and traditional CMS builds with structured content, intuitive editor flows, and APIs your frontend can consume from anywhere.',
                    'chips' => [
                        ['icon' => 'FileStack', 'label' => 'Structured content'],
                        ['icon' => 'Workflow', 'label' => 'Editorial workflows'],
                        ['icon' => 'Zap', 'label' => 'Fast publishing'],
                    ],
                    'primary_cta_label' => 'Start a CMS project',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A clean CMS admin interface showing content blocks, drafts, and a preview pane.',
                    'caption_eyebrow' => 'Editing experience',
                    'caption_text' => 'Inline previews, drafts, and roles built for real teams.',
                ],
                'tech' => [
                    'eyebrow' => 'CMS stack',
                    'heading_prefix' => 'Headless &',
                    'heading_highlight' => 'traditional CMS',
                    'description' => 'We pick the CMS that fits the team — Sanity or Strapi for structured content APIs, WordPress or Laravel for editorial-heavy sites.',
                    'items' => [
                        ['name' => 'Sanity', 'slug' => 'sanity'],
                        ['name' => 'Strapi', 'slug' => 'strapi'],
                        ['name' => 'Contentful', 'slug' => 'contentful'],
                        ['name' => 'WordPress', 'slug' => 'wordpress'],
                        ['name' => 'Laravel', 'slug' => 'laravel'],
                        ['name' => 'Next.js', 'slug' => 'nextdotjs'],
                    ],
                    'cta_label' => 'Plan a CMS migration',
                    'cta_href' => '/contact',
                    'image_alt' => 'CMS platform logos: Sanity, Strapi, Contentful, WordPress, Laravel, Next.js.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'CMS deliverables',
                    'description' => 'Editor-first content models, fast publishing pipelines, and APIs that scale with your traffic.',
                    'cards' => [
                        ['icon' => 'FileStack', 'title' => 'Content modelling', 'description' => 'Blocks, references, and taxonomies tuned to how your team actually writes.'],
                        ['icon' => 'Workflow', 'title' => 'Editorial workflows', 'description' => 'Drafts, scheduling, roles, approvals, and inline previews that prevent errors.'],
                        ['icon' => 'Zap', 'title' => 'Performance & SEO', 'description' => 'Cached APIs, ISR, structured data, and Core Web Vitals tracked from day one.'],
                    ],
                    'cta_label' => 'Talk to a CMS architect',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'web-development',
                'slug' => 'custom-web-applications',
                'title' => 'Custom Web Applications',
                'icon' => 'Box',
                'summary' => 'Dashboards, internal tools, and multi-tenant SaaS built on Laravel + Vue with predictable releases.',
                'meta_title' => 'Custom Web Application Development | Laravel & Vue Experts',
                'meta_description' => 'Bespoke web apps with Laravel and Vue — auth, roles, dashboards, observability, and CI/CD pipelines included from day one.',
                'meta_keywords' => 'custom web application development, saas development, laravel development, vue development, internal tools',
                'og_title' => 'Custom Web Application Development',
                'og_description' => 'Production-ready SaaS, dashboards, and internal tools shipped on Laravel + Vue with full observability.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Custom web apps',
                    'heading_prefix' => 'Reliable software,',
                    'heading_highlight' => 'shipped on schedule',
                    'subhead' => 'from MVP to multi-tenant SaaS',
                    'description' => 'Laravel + Vue web apps with auth, roles, queues, observability, and deploy pipelines so your team can iterate with confidence.',
                    'chips' => [
                        ['icon' => 'Database', 'label' => 'Solid data model'],
                        ['icon' => 'Shield', 'label' => 'Auth & roles'],
                        ['icon' => 'Activity', 'label' => 'Observability'],
                    ],
                    'primary_cta_label' => 'Scope your project',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'Analytics dashboard with charts, tables, and a clean side navigation built in a custom web application.',
                    'caption_eyebrow' => 'App layer',
                    'caption_text' => 'Roles, queues, jobs, and deploys — production-ready by default.',
                ],
                'tech' => [
                    'eyebrow' => 'Application stack',
                    'heading_prefix' => 'Modern PHP',
                    'heading_highlight' => '+ reactive frontend',
                    'description' => 'Battle-tested foundations with the flexibility to integrate the third-party services your business actually uses.',
                    'items' => [
                        ['name' => 'Laravel', 'slug' => 'laravel'],
                        ['name' => 'Vue.js', 'slug' => 'vuedotjs'],
                        ['name' => 'Inertia', 'slug' => 'inertia'],
                        ['name' => 'PostgreSQL', 'slug' => 'postgresql'],
                        ['name' => 'Redis', 'slug' => 'redis'],
                        ['name' => 'Tailwind CSS', 'slug' => 'tailwindcss'],
                    ],
                    'cta_label' => 'Plan an app build',
                    'cta_href' => '/contact',
                    'image_alt' => 'Laravel, Vue.js, Inertia, PostgreSQL, Redis, and Tailwind logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'What we ship',
                    'description' => 'Predictable milestones, strong defaults, and a codebase your engineers can own.',
                    'cards' => [
                        ['icon' => 'Box', 'title' => 'MVP to scale', 'description' => 'Launch fast, then grow with feature flags, queues, and observability already in place.'],
                        ['icon' => 'Shield', 'title' => 'Auth & permissions', 'description' => 'Multi-tenant ready, with roles, policies, and audit trails done right.'],
                        ['icon' => 'Activity', 'title' => 'CI/CD & monitoring', 'description' => 'Tested deploys, error tracking, and uptime monitoring before day one.'],
                    ],
                    'cta_label' => 'Talk to an architect',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'web-development',
                'slug' => 'ecommerce-development',
                'title' => 'E-commerce Development',
                'icon' => 'ShoppingCart',
                'summary' => 'Headless storefronts, Shopify, and custom checkouts engineered for conversion and operations.',
                'meta_title' => 'E-commerce Development Services | Shopify & Headless Storefronts',
                'meta_description' => 'Custom e-commerce builds — headless storefronts, Shopify, WooCommerce, and bespoke checkouts tuned for conversion, payments, and fulfillment.',
                'meta_keywords' => 'ecommerce development, shopify development, headless commerce, woocommerce, custom checkout, payment integration',
                'og_title' => 'E-commerce Development that Converts',
                'og_description' => 'Headless storefronts, Shopify, and custom checkouts built for conversion, payments, and operations.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'E-commerce',
                    'heading_prefix' => 'Storefronts',
                    'heading_highlight' => 'that ship & scale',
                    'subhead' => 'from launch to high-traffic events',
                    'description' => 'Catalog, cart, checkout, and fulfilment-aware storefronts built for the way your team actually merchandises and operates.',
                    'chips' => [
                        ['icon' => 'ShoppingCart', 'label' => 'Conversion-tuned'],
                        ['icon' => 'CreditCard', 'label' => 'Secure checkout'],
                        ['icon' => 'Package', 'label' => 'Fulfilment ready'],
                    ],
                    'primary_cta_label' => 'Plan your storefront',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'Modern e-commerce product page with crisp imagery, variants, and a streamlined add-to-cart flow.',
                    'caption_eyebrow' => 'Storefront layer',
                    'caption_text' => 'Optimised for Core Web Vitals and high-traffic launches.',
                ],
                'tech' => [
                    'eyebrow' => 'Commerce stack',
                    'heading_prefix' => 'Headless commerce',
                    'heading_highlight' => '+ proven platforms',
                    'description' => 'We build on the platform that fits your catalog, ops, and roadmap — not the other way around.',
                    'items' => [
                        ['name' => 'Shopify', 'slug' => 'shopify'],
                        ['name' => 'WooCommerce', 'slug' => 'woocommerce'],
                        ['name' => 'Stripe', 'slug' => 'stripe'],
                        ['name' => 'Next.js', 'slug' => 'nextdotjs'],
                        ['name' => 'Algolia', 'slug' => 'algolia'],
                        ['name' => 'Klaviyo', 'slug' => 'klaviyo'],
                    ],
                    'cta_label' => 'Discuss your storefront',
                    'cta_href' => '/contact',
                    'image_alt' => 'E-commerce platform logos: Shopify, WooCommerce, Stripe, Next.js, Algolia, Klaviyo.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Commerce deliverables',
                    'description' => 'Conversion-driven storefronts, secure checkouts, and integrations with the tools your business already uses.',
                    'cards' => [
                        ['icon' => 'ShoppingCart', 'title' => 'Conversion design', 'description' => 'PDP, PLP, cart, and checkout layouts engineered to remove friction and lift AOV.'],
                        ['icon' => 'CreditCard', 'title' => 'Payments & tax', 'description' => 'Stripe / PayPal / wallet integrations with fraud, tax, and refund handling baked in.'],
                        ['icon' => 'Package', 'title' => 'Operations & fulfilment', 'description' => 'OMS, ERP, and shipping integrations so the warehouse and storefront stay in sync.'],
                    ],
                    'cta_label' => 'Talk to a commerce engineer',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            // ============================== MOBILE APP DEVELOPMENT ==============================
            [
                'category' => 'mobile-development',
                'slug' => 'mobile-app-ui-ux',
                'title' => 'Mobile App UI/UX',
                'icon' => 'Sparkles',
                'summary' => 'Gesture-aware flows, performance-first layouts, and polish for App Store–ready products.',
                'meta_title' => 'Mobile App UI/UX Design Services | iOS & Android',
                'meta_description' => 'Mobile app UI/UX design across iOS and Android — gesture-aware flows, accessible layouts, and motion that ships smoothly to production.',
                'meta_keywords' => 'mobile app ui ux, ios design, android design, mobile design system, app design services',
                'og_title' => 'Mobile App UI/UX Design',
                'og_description' => 'Product-grade mobile UX with motion, accessibility, and design systems tuned for small screens.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Mobile UI / UX',
                    'heading_prefix' => 'Native-feeling apps,',
                    'heading_highlight' => 'down to the gesture',
                    'subhead' => 'designed for the way people actually use phones',
                    'description' => 'Information architecture, motion, and accessible layouts tuned for small screens, real performance budgets, and App Store / Play Store review.',
                    'chips' => [
                        ['icon' => 'Smartphone', 'label' => 'iOS + Android'],
                        ['icon' => 'Sparkles', 'label' => 'Motion & polish'],
                        ['icon' => 'Accessibility', 'label' => 'Accessibility built in'],
                    ],
                    'primary_cta_label' => 'Design my app',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A polished mobile onboarding flow shown across multiple smartphone screens with accent colors and clean typography.',
                    'caption_eyebrow' => 'Mobile layer',
                    'caption_text' => 'Designed for thumbs, tested on real devices.',
                ],
                'tech' => [
                    'eyebrow' => 'Mobile UX stack',
                    'heading_prefix' => 'Design',
                    'heading_highlight' => 'for both stores',
                    'description' => 'Apple HIG, Material 3, and motion patterns adapted into a unified design system for your product.',
                    'items' => [
                        ['name' => 'Figma', 'slug' => 'figma'],
                        ['name' => 'Lottie', 'slug' => 'lottiefiles'],
                        ['name' => 'Swift UI', 'slug' => 'swift'],
                        ['name' => 'Jetpack Compose', 'slug' => 'jetpackcompose'],
                        ['name' => 'React Native', 'slug' => 'react'],
                        ['name' => 'Flutter', 'slug' => 'flutter'],
                    ],
                    'cta_label' => 'Plan your mobile UX',
                    'cta_href' => '/contact',
                    'image_alt' => 'Logos for Figma, Lottie, SwiftUI, Jetpack Compose, React Native, and Flutter.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Mobile UX deliverables',
                    'description' => 'A coherent design system, store-ready visuals, and prototypes your engineers can build from.',
                    'cards' => [
                        ['icon' => 'Smartphone', 'title' => 'Cross-platform parity', 'description' => 'Shared system, native feel — visual rules for iOS and Android in one source of truth.'],
                        ['icon' => 'Sparkles', 'title' => 'Motion & micro-interactions', 'description' => 'Lottie animations, transitions, and haptics that make the app feel premium.'],
                        ['icon' => 'Accessibility', 'title' => 'Accessibility & QA', 'description' => 'Type scales, color contrast, focus order, and gesture audits across both platforms.'],
                    ],
                    'cta_label' => 'Talk to a mobile designer',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'mobile-development',
                'slug' => 'android-app-development',
                'title' => 'Android App Development',
                'icon' => 'Smartphone',
                'summary' => 'Kotlin and Jetpack Compose builds with Material 3, offline-first patterns, and Play-ready releases.',
                'meta_title' => 'Android App Development | Kotlin & Jetpack Compose Experts',
                'meta_description' => 'Native Android app development in Kotlin and Jetpack Compose — Material 3 UI, offline-first storage, and Play Store–compliant release pipelines.',
                'meta_keywords' => 'android app development, kotlin development, jetpack compose, native android apps, play store',
                'og_title' => 'Native Android App Development',
                'og_description' => 'Kotlin + Jetpack Compose Android apps with Material 3, offline-first storage, and Play-ready releases.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Android development',
                    'heading_prefix' => 'Native Android,',
                    'heading_highlight' => 'built to last',
                    'subhead' => 'with Kotlin & Jetpack Compose',
                    'description' => 'Modern Material 3 interfaces, MVVM architecture, offline-first storage, and CI pipelines that ship to internal, beta, and production tracks.',
                    'chips' => [
                        ['icon' => 'Smartphone', 'label' => 'Kotlin + Compose'],
                        ['icon' => 'Database', 'label' => 'Offline-first'],
                        ['icon' => 'Shield', 'label' => 'Play compliant'],
                    ],
                    'primary_cta_label' => 'Start an Android build',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'An Android phone showing a Material 3 app with a bottom navigation bar and modern color tokens.',
                    'caption_eyebrow' => 'Android layer',
                    'caption_text' => 'MVVM, Hilt, Compose, and a clean release pipeline.',
                ],
                'tech' => [
                    'eyebrow' => 'Android stack',
                    'heading_prefix' => 'Modern Android',
                    'heading_highlight' => 'engineering',
                    'description' => 'A pragmatic Android stack focused on testability, modularization, and a smooth path from local dev to the Play Store.',
                    'items' => [
                        ['name' => 'Kotlin', 'slug' => 'kotlin'],
                        ['name' => 'Jetpack Compose', 'slug' => 'jetpackcompose'],
                        ['name' => 'Android Studio', 'slug' => 'androidstudio'],
                        ['name' => 'Gradle', 'slug' => 'gradle'],
                        ['name' => 'Firebase', 'slug' => 'firebase'],
                        ['name' => 'Material Design', 'slug' => 'materialdesign'],
                    ],
                    'cta_label' => 'Plan your Android app',
                    'cta_href' => '/contact',
                    'image_alt' => 'Kotlin, Jetpack Compose, Android Studio, Gradle, Firebase, and Material Design logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Android deliverables',
                    'description' => 'Production-ready APKs with the testing, observability, and release tooling teams need.',
                    'cards' => [
                        ['icon' => 'Smartphone', 'title' => 'Native UI', 'description' => 'Compose-based screens, theming, and animations that feel made for the device.'],
                        ['icon' => 'Database', 'title' => 'Offline & sync', 'description' => 'Room, WorkManager, and conflict-aware sync for unreliable networks.'],
                        ['icon' => 'Shield', 'title' => 'Releases & analytics', 'description' => 'Play Console pipelines, Crashlytics, and analytics wired in from day one.'],
                    ],
                    'cta_label' => 'Talk to an Android engineer',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'mobile-development',
                'slug' => 'ios-app-development',
                'title' => 'iOS App Development',
                'icon' => 'TabletSmartphone',
                'summary' => 'SwiftUI + Combine apps that respect HIG, ship through TestFlight, and pass App Store review.',
                'meta_title' => 'iOS App Development Services | SwiftUI & Combine Experts',
                'meta_description' => 'Native iOS apps in SwiftUI and Combine, aligned to Apple HIG, delivered through TestFlight, and engineered to pass App Store review.',
                'meta_keywords' => 'ios app development, swift development, swiftui, combine, app store, testflight',
                'og_title' => 'Native iOS App Development',
                'og_description' => 'SwiftUI + Combine iOS apps tuned to Apple HIG, with TestFlight builds and App Store–ready releases.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'iOS development',
                    'heading_prefix' => 'iOS apps that',
                    'heading_highlight' => 'feel like Apple',
                    'subhead' => 'built with SwiftUI and Combine',
                    'description' => 'Modern Swift architecture, accessibility-friendly UI, secure data handling, and store releases coordinated from TestFlight to production.',
                    'chips' => [
                        ['icon' => 'TabletSmartphone', 'label' => 'SwiftUI + Combine'],
                        ['icon' => 'Lock', 'label' => 'Privacy-first'],
                        ['icon' => 'Rocket', 'label' => 'TestFlight ready'],
                    ],
                    'primary_cta_label' => 'Start an iOS build',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'An iPhone with a SwiftUI app showing a clean translucent navigation bar and SF Symbols.',
                    'caption_eyebrow' => 'iOS layer',
                    'caption_text' => 'HIG-aligned, accessible, and TestFlight-ready.',
                ],
                'tech' => [
                    'eyebrow' => 'iOS stack',
                    'heading_prefix' => 'Modern Apple',
                    'heading_highlight' => 'engineering',
                    'description' => 'Swift, SwiftUI, and Combine — with the Xcode tooling, signing, and CI you need to release on a schedule.',
                    'items' => [
                        ['name' => 'Swift', 'slug' => 'swift'],
                        ['name' => 'SwiftUI', 'slug' => 'swift'],
                        ['name' => 'Xcode', 'slug' => 'xcode'],
                        ['name' => 'Combine', 'slug' => 'apple'],
                        ['name' => 'TestFlight', 'slug' => 'apple'],
                        ['name' => 'Firebase', 'slug' => 'firebase'],
                    ],
                    'cta_label' => 'Plan your iOS app',
                    'cta_href' => '/contact',
                    'image_alt' => 'Swift, SwiftUI, Xcode, Apple, and Firebase logos arranged in a grid.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'iOS deliverables',
                    'description' => 'Apps that respect Apple guidelines, ship through TestFlight, and survive App Store review.',
                    'cards' => [
                        ['icon' => 'TabletSmartphone', 'title' => 'SwiftUI architecture', 'description' => 'MVVM/TCA-friendly architecture and reusable components from day one.'],
                        ['icon' => 'Lock', 'title' => 'Privacy & security', 'description' => 'Keychain, biometrics, and ATT done right — with App Privacy reports prepared.'],
                        ['icon' => 'Rocket', 'title' => 'Release pipeline', 'description' => 'Fastlane + Xcode Cloud automations to TestFlight and the App Store.'],
                    ],
                    'cta_label' => 'Talk to an iOS engineer',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'mobile-development',
                'slug' => 'cross-platform-app-development',
                'title' => 'Cross-Platform App Development',
                'icon' => 'Share2',
                'summary' => 'React Native and Flutter apps with shared logic, native modules, and per-platform polish.',
                'meta_title' => 'Cross-Platform App Development | React Native & Flutter',
                'meta_description' => 'Cross-platform mobile apps with React Native and Flutter — shared business logic, native modules where it matters, and per-platform polish.',
                'meta_keywords' => 'cross platform app development, react native development, flutter development, hybrid apps, mobile mvp',
                'og_title' => 'Cross-Platform App Development',
                'og_description' => 'React Native and Flutter apps with shared logic, native modules, and per-platform polish.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Cross-platform',
                    'heading_prefix' => 'One codebase,',
                    'heading_highlight' => 'two stores',
                    'subhead' => 'without losing the native feel',
                    'description' => 'React Native and Flutter apps where shared logic makes sense and native modules step in for camera, BLE, payments, and performance-sensitive work.',
                    'chips' => [
                        ['icon' => 'Share2', 'label' => 'RN + Flutter'],
                        ['icon' => 'Layers', 'label' => 'Native modules'],
                        ['icon' => 'Rocket', 'label' => 'Faster MVPs'],
                    ],
                    'primary_cta_label' => 'Plan a cross-platform app',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'iPhone and Android phone side by side running the same cross-platform mobile app.',
                    'caption_eyebrow' => 'Hybrid layer',
                    'caption_text' => 'Shared code where it pays off, native code where it matters.',
                ],
                'tech' => [
                    'eyebrow' => 'Cross-platform stack',
                    'heading_prefix' => 'Pragmatic',
                    'heading_highlight' => 'tooling',
                    'description' => 'Mature frameworks, typed APIs, and CI pipelines that build for both stores from the same repository.',
                    'items' => [
                        ['name' => 'React Native', 'slug' => 'react'],
                        ['name' => 'Expo', 'slug' => 'expo'],
                        ['name' => 'Flutter', 'slug' => 'flutter'],
                        ['name' => 'TypeScript', 'slug' => 'typescript'],
                        ['name' => 'Firebase', 'slug' => 'firebase'],
                        ['name' => 'GraphQL', 'slug' => 'graphql'],
                    ],
                    'cta_label' => 'Discuss your hybrid app',
                    'cta_href' => '/contact',
                    'image_alt' => 'React Native, Expo, Flutter, TypeScript, Firebase, and GraphQL logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Cross-platform deliverables',
                    'description' => 'Faster delivery to both stores with a codebase your team can keep evolving.',
                    'cards' => [
                        ['icon' => 'Share2', 'title' => 'Shared business logic', 'description' => 'TypeScript domain layer reused across iOS, Android, and the web client.'],
                        ['icon' => 'Layers', 'title' => 'Per-platform polish', 'description' => 'Native gestures, theming, and platform-specific micro-interactions.'],
                        ['icon' => 'Rocket', 'title' => 'CI for both stores', 'description' => 'Single pipeline producing signed builds for App Store Connect and Play Console.'],
                    ],
                    'cta_label' => 'Talk to a hybrid engineer',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            // ============================== AI SOLUTIONS ==============================
            [
                'category' => 'ai-solutions',
                'slug' => 'generative-ai',
                'title' => 'Generative AI Solutions',
                'icon' => 'Sparkles',
                'summary' => 'LLM-powered assistants, summarisation, and content workflows grounded in your data and guardrails.',
                'meta_title' => 'Generative AI Solutions | LLM Assistants, Summarisation, Workflows',
                'meta_description' => 'Generative AI solutions — LLM assistants, summarisation, and content workflows grounded in your data with policy-aware guardrails and observability.',
                'meta_keywords' => 'generative ai, llm assistants, openai integration, ai content generation, ai workflows',
                'og_title' => 'Generative AI Solutions',
                'og_description' => 'Practical LLM assistants and workflows grounded in your data with safety, evaluation, and observability built in.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Generative AI',
                    'heading_prefix' => 'Useful AI,',
                    'heading_highlight' => 'not gimmicks',
                    'subhead' => 'grounded in your data and your policies',
                    'description' => 'LLM assistants, summarisation pipelines, and content workflows wired to your domain — with eval, guardrails, and audit logs your team can trust.',
                    'chips' => [
                        ['icon' => 'Sparkles', 'label' => 'LLM workflows'],
                        ['icon' => 'Shield', 'label' => 'Policy-aware'],
                        ['icon' => 'Activity', 'label' => 'Eval + observability'],
                    ],
                    'primary_cta_label' => 'Plan a GenAI use case',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A clean chat interface showing an AI assistant answering a business question with cited sources.',
                    'caption_eyebrow' => 'AI layer',
                    'caption_text' => 'Grounded answers, with citations and eval baked in.',
                ],
                'tech' => [
                    'eyebrow' => 'GenAI stack',
                    'heading_prefix' => 'Models',
                    'heading_highlight' => '+ orchestration',
                    'description' => 'A layered architecture so you can swap providers, run evals, and version prompts like code.',
                    'items' => [
                        ['name' => 'OpenAI', 'slug' => 'openai'],
                        ['name' => 'Anthropic', 'slug' => 'anthropic'],
                        ['name' => 'LangChain', 'slug' => 'langchain'],
                        ['name' => 'LlamaIndex', 'slug' => 'meta'],
                        ['name' => 'Pinecone', 'slug' => 'pinecone'],
                        ['name' => 'Hugging Face', 'slug' => 'huggingface'],
                    ],
                    'cta_label' => 'Discuss your AI roadmap',
                    'cta_href' => '/contact',
                    'image_alt' => 'OpenAI, Anthropic, LangChain, LlamaIndex, Pinecone, and Hugging Face logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'GenAI deliverables',
                    'description' => 'AI features your customers actually use — with the rails to keep them safe and measurable.',
                    'cards' => [
                        ['icon' => 'Sparkles', 'title' => 'Assistants & copilots', 'description' => 'In-app chat and inline assistants grounded in your product data.'],
                        ['icon' => 'Shield', 'title' => 'Guardrails & eval', 'description' => 'Prompt versioning, regression eval suites, and policy filters from day one.'],
                        ['icon' => 'Activity', 'title' => 'Observability', 'description' => 'Cost, latency, and quality dashboards for every prompt in production.'],
                    ],
                    'cta_label' => 'Plan a pilot',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'ai-solutions',
                'slug' => 'voice-ai',
                'title' => 'Voice AI Solutions',
                'icon' => 'Mic',
                'summary' => 'Speech interfaces, transcription pipelines, and conversational UX with clear fallbacks.',
                'meta_title' => 'Voice AI Solutions | Speech, Transcription & Conversational UX',
                'meta_description' => 'Voice AI products — speech-to-text, text-to-speech, conversational agents, and call workflows engineered with low latency and graceful fallbacks.',
                'meta_keywords' => 'voice ai, speech recognition, text to speech, conversational ai, ivr, call center ai',
                'og_title' => 'Voice AI Solutions',
                'og_description' => 'Speech-to-text, conversational agents, and call workflows with low latency and graceful fallbacks.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Voice AI',
                    'heading_prefix' => 'Conversations,',
                    'heading_highlight' => 'in your product',
                    'subhead' => 'with realistic latency and clean fallbacks',
                    'description' => 'Speech-to-text, text-to-speech, and conversational agents tuned for noisy environments, multilingual users, and the realities of telephony.',
                    'chips' => [
                        ['icon' => 'Mic', 'label' => 'STT + TTS'],
                        ['icon' => 'PhoneCall', 'label' => 'Telephony ready'],
                        ['icon' => 'Languages', 'label' => 'Multilingual'],
                    ],
                    'primary_cta_label' => 'Plan a voice pilot',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'Voice waveform animation overlaid on a chat interface showing real-time transcription.',
                    'caption_eyebrow' => 'Voice layer',
                    'caption_text' => 'Streaming STT, lifelike TTS, and graceful fallbacks.',
                ],
                'tech' => [
                    'eyebrow' => 'Voice stack',
                    'heading_prefix' => 'Best-in-class',
                    'heading_highlight' => 'speech tools',
                    'description' => 'Battle-tested speech APIs and orchestration so you can ship voice without owning the model layer.',
                    'items' => [
                        ['name' => 'Whisper', 'slug' => 'openai'],
                        ['name' => 'Deepgram', 'slug' => 'deepgram'],
                        ['name' => 'ElevenLabs', 'slug' => 'elevenlabs'],
                        ['name' => 'Twilio', 'slug' => 'twilio'],
                        ['name' => 'Vapi', 'slug' => 'vapi'],
                        ['name' => 'Google Cloud', 'slug' => 'googlecloud'],
                    ],
                    'cta_label' => 'Discuss your voice use case',
                    'cta_href' => '/contact',
                    'image_alt' => 'Whisper, Deepgram, ElevenLabs, Twilio, and Google Cloud logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Voice AI deliverables',
                    'description' => 'Conversational features that work — even on bad networks, in noisy rooms, and with diverse accents.',
                    'cards' => [
                        ['icon' => 'Mic', 'title' => 'Streaming STT', 'description' => 'Sub-second partial transcripts and noise-robust models for live use cases.'],
                        ['icon' => 'PhoneCall', 'title' => 'Conversational agents', 'description' => 'IVR replacements, voice copilots, and call summarisation with clean handoff.'],
                        ['icon' => 'Languages', 'title' => 'Multilingual & accessible', 'description' => 'Locale-aware prompts, captions, and TTS voices that read well to everyone.'],
                    ],
                    'cta_label' => 'Plan a voice pilot',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'ai-solutions',
                'slug' => 'custom-ai-model-integration',
                'title' => 'Custom AI Model Integration',
                'icon' => 'Cpu',
                'summary' => 'Inference pipelines, evaluation harnesses, and cost-aware deployment for proprietary or fine-tuned models.',
                'meta_title' => 'Custom AI Model Integration | Inference, Eval & Deployment',
                'meta_description' => 'Integrate proprietary or fine-tuned AI models into your stack with inference pipelines, evaluation harnesses, and cost-aware deployment.',
                'meta_keywords' => 'custom ai integration, model fine-tuning, ai inference, mlops, model deployment, model evaluation',
                'og_title' => 'Custom AI Model Integration',
                'og_description' => 'Inference pipelines, evaluation harnesses, and cost-aware deployment for proprietary and fine-tuned AI models.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Custom AI integration',
                    'heading_prefix' => 'Your models,',
                    'heading_highlight' => 'in production',
                    'subhead' => 'with cost, eval, and rollback under control',
                    'description' => 'We wire fine-tuned, hosted, or self-hosted models into your product with batched inference, A/B testing, and the observability MLOps demands.',
                    'chips' => [
                        ['icon' => 'Cpu', 'label' => 'Inference pipelines'],
                        ['icon' => 'TestTube', 'label' => 'Eval harness'],
                        ['icon' => 'TrendingDown', 'label' => 'Cost-aware'],
                    ],
                    'primary_cta_label' => 'Plan an integration',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A monitoring dashboard showing model latency, cost per call, and eval scores trending over time.',
                    'caption_eyebrow' => 'MLOps layer',
                    'caption_text' => 'Versioned prompts, eval suites, and cost dashboards.',
                ],
                'tech' => [
                    'eyebrow' => 'MLOps stack',
                    'heading_prefix' => 'Inference,',
                    'heading_highlight' => 'eval & deploy',
                    'description' => 'A pragmatic MLOps stack — open weights when it makes sense, hosted APIs when it doesn’t, observability across both.',
                    'items' => [
                        ['name' => 'Hugging Face', 'slug' => 'huggingface'],
                        ['name' => 'AWS', 'slug' => 'amazonwebservices'],
                        ['name' => 'Modal', 'slug' => 'modal'],
                        ['name' => 'Replicate', 'slug' => 'replicate'],
                        ['name' => 'Weights & Biases', 'slug' => 'weightsandbiases'],
                        ['name' => 'Vercel', 'slug' => 'vercel'],
                    ],
                    'cta_label' => 'Talk to an MLOps engineer',
                    'cta_href' => '/contact',
                    'image_alt' => 'Hugging Face, AWS, Modal, Replicate, Weights & Biases, and Vercel logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Integration deliverables',
                    'description' => 'A production-grade pathway from notebook to deployed feature — with the safety nets to keep iterating.',
                    'cards' => [
                        ['icon' => 'Cpu', 'title' => 'Inference services', 'description' => 'Batched, streamed, or on-device inference with sensible caching and retries.'],
                        ['icon' => 'TestTube', 'title' => 'Eval & A/B', 'description' => 'Regression suites, golden datasets, and live A/B with real user signals.'],
                        ['icon' => 'TrendingDown', 'title' => 'Cost & latency', 'description' => 'Quantisation, routing, and caching to hit the price/quality you need.'],
                    ],
                    'cta_label' => 'Discuss your model rollout',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'ai-solutions',
                'slug' => 'rag-retrieval-systems',
                'title' => 'RAG & Retrieval Systems',
                'icon' => 'Database',
                'summary' => 'Retrieval-augmented answers with citations, guardrails, and observability for trustworthy AI.',
                'meta_title' => 'RAG & Retrieval Systems | Trustworthy AI Answers with Citations',
                'meta_description' => 'Retrieval-augmented generation for trustworthy AI — vector indexes, hybrid search, citations, guardrails, and full observability.',
                'meta_keywords' => 'rag, retrieval augmented generation, vector search, embeddings, ai citations, ai grounding',
                'og_title' => 'RAG & Retrieval Systems',
                'og_description' => 'Trustworthy retrieval-augmented AI with vector + hybrid search, citations, and guardrails.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'RAG & retrieval',
                    'heading_prefix' => 'Answers',
                    'heading_highlight' => 'you can cite',
                    'subhead' => 'grounded in your own knowledge base',
                    'description' => 'Vector + keyword hybrid retrieval, chunking that respects structure, and prompt patterns that produce answers with verifiable citations.',
                    'chips' => [
                        ['icon' => 'Database', 'label' => 'Vector + hybrid'],
                        ['icon' => 'Quote', 'label' => 'Citations'],
                        ['icon' => 'Shield', 'label' => 'Guardrails'],
                    ],
                    'primary_cta_label' => 'Plan a RAG pilot',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'AI answer panel with inline citation chips linked to source documents.',
                    'caption_eyebrow' => 'Knowledge layer',
                    'caption_text' => 'Hybrid retrieval, ranked context, and citations users trust.',
                ],
                'tech' => [
                    'eyebrow' => 'RAG stack',
                    'heading_prefix' => 'Embeddings,',
                    'heading_highlight' => 'indexes & rerankers',
                    'description' => 'A modern retrieval stack tuned for throughput, latency, and the long-tail accuracy real users need.',
                    'items' => [
                        ['name' => 'pgvector', 'slug' => 'postgresql'],
                        ['name' => 'Pinecone', 'slug' => 'pinecone'],
                        ['name' => 'Qdrant', 'slug' => 'qdrant'],
                        ['name' => 'OpenAI', 'slug' => 'openai'],
                        ['name' => 'Cohere', 'slug' => 'cohere'],
                        ['name' => 'LlamaIndex', 'slug' => 'meta'],
                    ],
                    'cta_label' => 'Talk to a RAG engineer',
                    'cta_href' => '/contact',
                    'image_alt' => 'pgvector, Pinecone, Qdrant, OpenAI, Cohere, and LlamaIndex logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'RAG deliverables',
                    'description' => 'Trustworthy AI answers grounded in your data with the eval and observability to keep them honest.',
                    'cards' => [
                        ['icon' => 'Database', 'title' => 'Indexing pipeline', 'description' => 'Connectors, chunking, embeddings, and re-indexing on a schedule.'],
                        ['icon' => 'Quote', 'title' => 'Cited responses', 'description' => 'Inline citations and answer formats that users can verify in one click.'],
                        ['icon' => 'Shield', 'title' => 'Guardrails & eval', 'description' => 'Refusal logic, PII filters, and a regression eval suite for every release.'],
                    ],
                    'cta_label' => 'Plan your RAG rollout',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            // ============================== DIGITAL MARKETING ==============================
            [
                'category' => 'digital-marketing',
                'slug' => 'seo-services',
                'title' => 'SEO Services',
                'icon' => 'Search',
                'summary' => 'Technical SEO, structured data, and performance budgets that search engines reward.',
                'meta_title' => 'SEO Services | Technical SEO, Structured Data & Core Web Vitals',
                'meta_description' => 'SEO services covering technical SEO audits, structured data, Core Web Vitals, content strategy, and reporting that proves search-driven growth.',
                'meta_keywords' => 'seo services, technical seo, structured data, core web vitals, on page seo, seo audit',
                'og_title' => 'Technical SEO that Drives Growth',
                'og_description' => 'Technical SEO, structured data, performance budgets, and content strategy with reporting that proves growth.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'SEO services',
                    'heading_prefix' => 'Search growth,',
                    'heading_highlight' => 'engineered',
                    'subhead' => 'for the way modern search actually ranks',
                    'description' => 'Technical SEO audits, schema markup, internal linking, content strategy, and Core Web Vitals work tied to revenue, not vanity metrics.',
                    'chips' => [
                        ['icon' => 'Search', 'label' => 'Technical SEO'],
                        ['icon' => 'Code', 'label' => 'Schema & meta'],
                        ['icon' => 'Activity', 'label' => 'Vitals + reporting'],
                    ],
                    'primary_cta_label' => 'Request an SEO audit',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'An SEO dashboard with rising organic traffic charts, Core Web Vitals scores, and keyword rankings.',
                    'caption_eyebrow' => 'Search layer',
                    'caption_text' => 'Audited, instrumented, and tied to revenue.',
                ],
                'tech' => [
                    'eyebrow' => 'SEO stack',
                    'heading_prefix' => 'Tools',
                    'heading_highlight' => 'we run',
                    'description' => 'Industry-standard tools paired with custom dashboards so insights are actionable, not just observable.',
                    'items' => [
                        ['name' => 'Google Search Console', 'slug' => 'googlesearchconsole'],
                        ['name' => 'Google Analytics', 'slug' => 'googleanalytics'],
                        ['name' => 'Ahrefs', 'slug' => 'ahrefs'],
                        ['name' => 'Semrush', 'slug' => 'semrush'],
                        ['name' => 'Screaming Frog', 'slug' => 'screamingfrog'],
                        ['name' => 'Looker', 'slug' => 'looker'],
                    ],
                    'cta_label' => 'Plan an SEO sprint',
                    'cta_href' => '/contact',
                    'image_alt' => 'Search Console, Analytics, Ahrefs, Semrush, Screaming Frog, and Looker logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'SEO deliverables',
                    'description' => 'Audits, fixes, and content programs that compound — with reporting your stakeholders can read.',
                    'cards' => [
                        ['icon' => 'Search', 'title' => 'Technical audit', 'description' => 'Crawl, index, schema, hreflang, and Core Web Vitals issues prioritised by impact.'],
                        ['icon' => 'Code', 'title' => 'Structured data', 'description' => 'Article, Product, FAQ, and Service schema validated against Google’s rich-results spec.'],
                        ['icon' => 'Activity', 'title' => 'Reporting & growth', 'description' => 'Monthly dashboards, content roadmap, and conversions tracked end-to-end.'],
                    ],
                    'cta_label' => 'Talk to an SEO strategist',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'digital-marketing',
                'slug' => 'social-media-marketing',
                'title' => 'Social Media Marketing',
                'icon' => 'Share2',
                'summary' => 'Campaign-ready landing pages, tracking, and creative iteration loops across paid and organic.',
                'meta_title' => 'Social Media Marketing Services | Paid + Organic Campaigns',
                'meta_description' => 'Social media marketing across Meta, TikTok, LinkedIn, and X — campaign landing pages, conversion tracking, and creative iteration that scales.',
                'meta_keywords' => 'social media marketing, paid social, meta ads, tiktok ads, linkedin ads, organic social',
                'og_title' => 'Social Media Marketing that Scales',
                'og_description' => 'Paid + organic social campaigns with landing pages, tracking, and a creative iteration loop tied to revenue.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'Social media',
                    'heading_prefix' => 'Campaigns',
                    'heading_highlight' => 'that compound',
                    'subhead' => 'across paid and organic social',
                    'description' => 'Strategy, creative, landing pages, and analytics for Meta, TikTok, LinkedIn, and X — with a tested iteration loop instead of guesswork.',
                    'chips' => [
                        ['icon' => 'Share2', 'label' => 'Paid + organic'],
                        ['icon' => 'Image', 'label' => 'Creative ops'],
                        ['icon' => 'BarChart3', 'label' => 'Tracked end-to-end'],
                    ],
                    'primary_cta_label' => 'Plan a social campaign',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A grid of branded social media creatives across formats — story, reel, and feed.',
                    'caption_eyebrow' => 'Social layer',
                    'caption_text' => 'Creatives, audiences, and landing pages working together.',
                ],
                'tech' => [
                    'eyebrow' => 'Social stack',
                    'heading_prefix' => 'Channels',
                    'heading_highlight' => 'we run',
                    'description' => 'A focused mix of platforms, plus the tracking and creative tooling that keeps campaigns measurable.',
                    'items' => [
                        ['name' => 'Meta Ads', 'slug' => 'meta'],
                        ['name' => 'TikTok', 'slug' => 'tiktok'],
                        ['name' => 'LinkedIn', 'slug' => 'linkedin'],
                        ['name' => 'X', 'slug' => 'x'],
                        ['name' => 'YouTube', 'slug' => 'youtube'],
                        ['name' => 'Google Tag Manager', 'slug' => 'googletagmanager'],
                    ],
                    'cta_label' => 'Plan a campaign',
                    'cta_href' => '/contact',
                    'image_alt' => 'Meta, TikTok, LinkedIn, X, YouTube, and Google Tag Manager logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Social deliverables',
                    'description' => 'Creative that performs, audiences that compound, and a measurement layer that ties every dollar to revenue.',
                    'cards' => [
                        ['icon' => 'Share2', 'title' => 'Paid social management', 'description' => 'Audience research, creative briefs, weekly optimisation, and clear pacing.'],
                        ['icon' => 'Image', 'title' => 'Organic content', 'description' => 'Editorial calendars, creator collabs, and on-brand assets shipped on a cadence.'],
                        ['icon' => 'BarChart3', 'title' => 'Tracking & attribution', 'description' => 'GTM, CAPI, UTM hygiene, and dashboards that show payback by channel.'],
                    ],
                    'cta_label' => 'Talk to a social strategist',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'digital-marketing',
                'slug' => 'ppc-advertising',
                'title' => 'PPC Advertising',
                'icon' => 'Target',
                'summary' => 'Conversion tracking, experiments, and landing pages aligned to bids on Google, Microsoft, and beyond.',
                'meta_title' => 'PPC Advertising Services | Google, Microsoft & High-Intent Search',
                'meta_description' => 'PPC management for Google Ads, Microsoft Ads, and high-intent search — conversion tracking, experiments, and landing pages aligned to bids.',
                'meta_keywords' => 'ppc advertising, google ads management, microsoft ads, paid search, conversion tracking, landing page optimisation',
                'og_title' => 'PPC Advertising that Pays Back',
                'og_description' => 'Search, shopping, and performance max with rigorous tracking and experiments aligned to revenue.',
                'schema_type' => 'Service',
                'hero' => [
                    'eyebrow' => 'PPC',
                    'heading_prefix' => 'Paid search,',
                    'heading_highlight' => 'profitable',
                    'subhead' => 'every account, every quarter',
                    'description' => 'Search, shopping, and Performance Max campaigns with rigorous bidding, tracking, and landing pages designed to convert the bids you’re paying for.',
                    'chips' => [
                        ['icon' => 'Target', 'label' => 'Search + shopping'],
                        ['icon' => 'Activity', 'label' => 'Conversion tracking'],
                        ['icon' => 'Beaker', 'label' => 'Experiments'],
                    ],
                    'primary_cta_label' => 'Audit my PPC',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'PPC dashboard showing CPC, CPA, and ROAS trends with conversion funnels.',
                    'caption_eyebrow' => 'Paid layer',
                    'caption_text' => 'Bid strategy, creative, and landing pages tuned together.',
                ],
                'tech' => [
                    'eyebrow' => 'PPC stack',
                    'heading_prefix' => 'Networks',
                    'heading_highlight' => '+ tooling',
                    'description' => 'Major paid networks plus the analytics and CRO tools that turn impressions into measurable revenue.',
                    'items' => [
                        ['name' => 'Google Ads', 'slug' => 'googleads'],
                        ['name' => 'Microsoft Ads', 'slug' => 'microsoftbing'],
                        ['name' => 'Google Analytics', 'slug' => 'googleanalytics'],
                        ['name' => 'GTM', 'slug' => 'googletagmanager'],
                        ['name' => 'Hotjar', 'slug' => 'hotjar'],
                        ['name' => 'Looker Studio', 'slug' => 'looker'],
                    ],
                    'cta_label' => 'Plan a PPC sprint',
                    'cta_href' => '/contact',
                    'image_alt' => 'Google Ads, Microsoft Ads, Google Analytics, GTM, Hotjar, and Looker Studio logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'PPC deliverables',
                    'description' => 'Profitable accounts, healthy quality scores, and reporting your finance team can audit.',
                    'cards' => [
                        ['icon' => 'Target', 'title' => 'Account architecture', 'description' => 'Campaign structure, keyword themes, and negatives tuned to your margins.'],
                        ['icon' => 'Activity', 'title' => 'Tracking & attribution', 'description' => 'Enhanced conversions, offline events, and server-side tagging done right.'],
                        ['icon' => 'Beaker', 'title' => 'Landing & CRO', 'description' => 'Search-intent landing pages and ongoing CRO experiments backed by data.'],
                    ],
                    'cta_label' => 'Talk to a PPC strategist',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],

            [
                'category' => 'digital-marketing',
                'slug' => 'content-writing',
                'title' => 'Content Writing',
                'icon' => 'PenLine',
                'summary' => 'Clear product narrative, docs, and on-site copy that supports discovery and conversion.',
                'meta_title' => 'Content Writing Services | Product, SEO & Long-Form Content',
                'meta_description' => 'Editorial content writing — product narrative, SEO articles, docs, and conversion copy that ranks, reads well, and supports discovery.',
                'meta_keywords' => 'content writing services, seo content, product copywriting, editorial content, technical writing',
                'og_title' => 'Content Writing that Ranks & Reads',
                'og_description' => 'Editorial-grade copy, SEO articles, and product narrative that supports discovery and conversion.',
                'schema_type' => 'CreativeWork',
                'hero' => [
                    'eyebrow' => 'Content writing',
                    'heading_prefix' => 'Words',
                    'heading_highlight' => 'that work',
                    'subhead' => 'for search, sales, and your customer',
                    'description' => 'Product narrative, SEO articles, and on-site copy backed by research, briefed against keywords, and edited like real publishing — not LLM slop.',
                    'chips' => [
                        ['icon' => 'PenLine', 'label' => 'Briefs + drafts'],
                        ['icon' => 'BookOpen', 'label' => 'Editorial standards'],
                        ['icon' => 'Search', 'label' => 'SEO-aware'],
                    ],
                    'primary_cta_label' => 'Plan content',
                    'primary_cta_href' => '/contact',
                    'secondary_cta_label' => 'All services',
                    'secondary_cta_href' => '/services',
                    'image_alt' => 'A clean editor view of an article in progress with structured headings and inline notes.',
                    'caption_eyebrow' => 'Editorial layer',
                    'caption_text' => 'Briefs, drafts, edits, and publishing — like a real newsroom.',
                ],
                'tech' => [
                    'eyebrow' => 'Editorial stack',
                    'heading_prefix' => 'Tools',
                    'heading_highlight' => 'we ship with',
                    'description' => 'A focused stack so research, drafting, editing, and publishing all happen in the same workflow.',
                    'items' => [
                        ['name' => 'Notion', 'slug' => 'notion'],
                        ['name' => 'Google Docs', 'slug' => 'googledocs'],
                        ['name' => 'Grammarly', 'slug' => 'grammarly'],
                        ['name' => 'Ahrefs', 'slug' => 'ahrefs'],
                        ['name' => 'Surfer SEO', 'slug' => 'surfer'],
                        ['name' => 'WordPress', 'slug' => 'wordpress'],
                    ],
                    'cta_label' => 'Brief a content sprint',
                    'cta_href' => '/contact',
                    'image_alt' => 'Notion, Google Docs, Grammarly, Ahrefs, Surfer SEO, and WordPress logos.',
                ],
                'outcomes' => [
                    'eyebrow' => 'Outcomes',
                    'heading' => 'Content deliverables',
                    'description' => 'A reliable content engine — briefs, drafts, edits, and SEO updates that ship on a cadence.',
                    'cards' => [
                        ['icon' => 'PenLine', 'title' => 'Editorial calendar', 'description' => 'Topic clusters, pillar pages, and a quarterly content plan with owners.'],
                        ['icon' => 'BookOpen', 'title' => 'On-site copy', 'description' => 'Product, marketing, and onboarding copy that turns visitors into users.'],
                        ['icon' => 'Search', 'title' => 'SEO updates', 'description' => 'Refreshes, internal links, and topical authority work that lifts existing pages.'],
                    ],
                    'cta_label' => 'Talk to an editor',
                    'cta_href' => '/contact',
                    'image_alt' => '',
                ],
            ],
        ];
    }
}
