/** Lucide icon names supported by SiteFooter.vue */
export const FOOTER_LINK_ICONS = [
  'HelpCircle',
  'Compass',
  'Mail',
  'Briefcase',
  'Library',
  'Newspaper',
  'Map',
  'Bot',
  'LayoutGrid',
  'Monitor',
  'Smartphone',
  'Cpu',
  'TrendingUp',
  'FolderKanban',
  'Star',
  'Send',
  'Code2',
  'Layers',
  'Gauge',
  'Cloud',
  'FolderOpen',
  'BookOpen',
  'FileText',
  'Rocket',
  'Users',
  'ClipboardCheck',
  'Scale',
  'Shield',
  'Eye',
  'ChevronRight',
  'ExternalLink',
]

export const FOOTER_SECTION_ICONS = [
  'Library',
  'Package',
  'ShoppingBag',
  'Lightbulb',
  'LineChart',
  'Target',
  'MessageSquare',
]
